<?php

return [
    [
        'name' => 'Amit Verma',
        'initials' => 'AV',
        'avatar_color' => 'bg-emerald-600',
        'location' => 'Raipur, Chhattisgarh',
        'rating' => 5,
        'relative_date' => '2 weeks ago',
        'style' => 'Realism',
        'content' => 'Dharam Sahu is an absolute genius! Got a hyper-realistic lion portrait on my forearm, and the level of detail is mind-blowing. The studio is extremely clean, modern, and hygienic. Best place in Chhattisgarh for custom tattoos!',
    ],
    [
        'name' => 'Sneha Dewangan',
        'initials' => 'SD',
        'avatar_color' => 'bg-indigo-600',
        'location' => 'Bhilai, Chhattisgarh',
        'rating' => 5,
        'relative_date' => '1 month ago',
        'style' => 'Mandala',
        'content' => 'Absolutely in love with my mandala sleeve. The dotwork and geometric precision is perfect. Dharam took his time to understand my vision and custom-designed the pattern. Highly professional!',
    ],
    [
        'name' => 'Vikram Singh',
        'initials' => 'VS',
        'avatar_color' => 'bg-amber-600',
        'location' => 'Raipur, Chhattisgarh',
        'rating' => 5,
        'relative_date' => '3 weeks ago',
        'style' => 'Spiritual',
        'content' => 'Got my first tattoo here, a custom spiritual Shiva design. The shading and fine lines are incredibly clean. The team makes you feel very comfortable throughout the process. Highly recommend Chinhari!',
    ],
    [
        'name' => 'Rahul Sharma',
        'initials' => 'RS',
        'avatar_color' => 'bg-rose-600',
        'location' => 'Raipur, Chhattisgarh',
        'rating' => 5,
        'relative_date' => '2 months ago',
        'style' => 'Portrait',
        'content' => 'Best tattoo artist in Raipur. Dharam Sahu\'s hand is very stable and details are absolutely perfect. Very clean environment and friendly behavior by all staff members.',
    ],
    [
        'name' => 'Priya Sen',
        'initials' => 'PS',
        'avatar_color' => 'bg-teal-600',
        'location' => 'Durg, Chhattisgarh',
        'rating' => 5,
        'relative_date' => '1 month ago',
        'style' => 'Fine Line',
        'content' => 'Extremely hygienic studio. They unpacked brand new needles and sterilized the equipment right in front of me. Highly professional behavior and excellent suggestions for aftercare.',
    ],
    [
        'name' => 'Abhishek K.',
        'initials' => 'AK',
        'avatar_color' => 'bg-sky-600',
        'location' => 'Raipur, Chhattisgarh',
        'rating' => 5,
        'relative_date' => '3 months ago',
        'style' => 'Cover Up',
        'content' => 'Amazing cover-up work! Dharam designed a custom polynesian pattern that completely hid my old faded tattoo. You cannot even tell there was an old tattoo underneath. Highly recommended!',
    ],
];
